### ISSUE TITLE
support for prestosql 332

### ISSUE THREAD

**Issue by tooptoop4** [shubhamtagra/infoschemaquerykiller#1]
https://github.com/prestosql/presto/issues/3219#issuecomment-603514310 mentions this won't work anymore as eventlistener won't be able to kill the query.

any way forward?

**Comment by shubhamtagra** [comment]
We can try exploring submitting DELETE to server for the query. 
DELETE on `v1/statement` wont work as there is slug check there now. But DELETE on `v1/query` can work but might be tricky in system with access-controls set up
